import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body>
        <nav className="main-nav">
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
          <div className="dropdown">
            <span className="dropdown-label">Services ▼</span>
            <div className="dropdown-content">
              <Link href="/services/maintenance">Maintenance</Link>
              <Link href="/services/modernization">Modernization</Link>
              <Link href="/services/relocation">Relocation</Link>
              <Link href="/services/spare-parts">Spare Parts</Link>
              <Link href="/services/tooling">Tooling</Link>
            </div>
          </div>
          <Link href="/parts-tooling">Parts & Tooling</Link>
          <Link href="/news">News & Downloads</Link>
          <Link href="/partners">Partners</Link>
          <Link href="/references">References</Link>
          <Link href="/career">Career</Link>
          <Link href="/contact">Contact</Link>
        </nav>
        <main>{children}</main>
        <footer style={{ marginTop: '2rem', padding: '1rem', background: '#222', color: '#fff', textAlign: 'center' }}>
          <div>Contact: info@mfsupport.com | +31 (0) 26 479 999 9</div>
          <div>© 2025 MFS Replica</div>
        </footer>
      </body>
    </html>
  );
}
